/**
 * Download Google Fonts (Fraunces + Inter + JetBrains Mono) into the theme so
 * the site self-hosts them instead of hitting the Google CDN.
 *
 * Fetches the css2 stylesheet with a modern Chrome UA (→ woff2), keeps the
 * latin + latin-ext subsets, downloads each file into assets/fonts/, rewrites
 * the @font-face src to a local relative path, and writes assets/fonts/fonts.css.
 *
 * Run:  node tools/fetch-fonts.mjs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname( fileURLToPath( import.meta.url ) );
const fontsDir = join( __dirname, '..', 'assets', 'fonts' );

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// Variable axes → one woff2 per subset, keeps the file count small.
const CSS_URL = 'https://fonts.googleapis.com/css2'
	+ '?family=Fraunces:ital,opsz,wght@0,9..144,400..600;1,9..144,400..500'
	+ '&family=Inter:wght@400..700'
	+ '&family=JetBrains+Mono:wght@400..500'
	+ '&display=swap';

const KEEP_SUBSETS = [ 'latin', 'latin-ext' ];

async function main() {
	const res = await fetch( CSS_URL, { headers: { 'User-Agent': UA } } );
	if ( ! res.ok ) throw new Error( `CSS fetch failed: ${ res.status }` );
	let css = await res.text();

	// Split into @font-face blocks, each preceded by a /* subset */ comment.
	const blocks = css.split( /(?=\/\*\s*[\w-]+\s*\*\/)/ );
	const out = [];
	const downloads = new Map(); // url -> local filename

	for ( const block of blocks ) {
		const subsetMatch = block.match( /\/\*\s*([\w-]+)\s*\*\// );
		const subset = subsetMatch ? subsetMatch[ 1 ] : '';
		if ( ! block.includes( '@font-face' ) ) continue;
		if ( ! KEEP_SUBSETS.includes( subset ) ) continue;

		const fam = ( block.match( /font-family:\s*'([^']+)'/ ) || [] )[ 1 ] || 'font';
		const style = /font-style:\s*italic/.test( block ) ? 'italic' : 'normal';
		const urlMatch = block.match( /url\(([^)]+\.woff2)\)/ );
		if ( ! urlMatch ) continue;
		const url = urlMatch[ 1 ];

		const slug = fam.toLowerCase().replace( /\s+/g, '-' );
		const file = `${ slug }-${ subset }${ style === 'italic' ? '-italic' : '' }.woff2`;
		downloads.set( url, file );

		out.push( block.trim().replace( /url\([^)]+\.woff2\)/, `url(./${ file })` ) );
	}

	for ( const [ url, file ] of downloads ) {
		const r = await fetch( url, { headers: { 'User-Agent': UA } } );
		if ( ! r.ok ) throw new Error( `font fetch failed (${ r.status }): ${ url }` );
		const buf = Buffer.from( await r.arrayBuffer() );
		writeFileSync( join( fontsDir, file ), buf );
		console.log( `  ↓ ${ file } (${ ( buf.length / 1024 ).toFixed( 1 ) } KB)` );
	}

	const header = '/* Self-hosted webfonts — generated by tools/fetch-fonts.mjs. Do not edit by hand. */\n\n';
	writeFileSync( join( fontsDir, 'fonts.css' ), header + out.join( '\n\n' ) + '\n' );
	console.log( `✓ Wrote fonts.css with ${ out.length } @font-face rules, ${ downloads.size } files` );
}

main().catch( ( e ) => { console.error( e ); process.exit( 1 ); } );
